version: 0.0
os: linux
files:
- source: /
  destination: /home/ec2-user
hooks:
  BeforeInstall:
  - location: scripts/before_install.sh
    timeout: 60
    runas: root
  AfterInstall:
  - location: scripts/after_install.sh
    timeout: 60
    runas: root
  ApplicationStart:
  - location: scripts/start_application.sh
    timeout: 60
    runas: root
  ApplicationStop:
  - location: scripts/stop_application.sh
    timeout: 60
    runas: root