version: 0.0
os: linux
files:
- source: /
  destination: /home/ec2-user
hooks:
  BeforeInstall:
  - location: scripts/before_install.sh
    timeout: 60
    runas: ec2-user
  AfterInstall:
  - location: scripts/after_install.sh
    timeout: 60
    runas: ec2-user
  ApplicationStart:
  - location: scripts/start_application.sh
    timeout: 60
    runas: ec2-user
  ApplicationStop:
  - location: scripts/stop_application.sh
    timeout: 60
    runas: ec2-user